V20190527

diff --git a/bin/STARK b/bin/STARK
--- a/bin/STARK
+++ b/bin/STARK
@@ -43,7 +43,7 @@ function release () {
 
 # Usage
 function usage {
-	echo "# USAGE: $(basename $0) --analysis=<FILE>|--reads=<FASTQ>|--runs=<RUN> [options...]";
+	echo "# USAGE: $(basename $0) --analysis=<FILE>|--reads=<FASTQ>|--run=<RUN> [options...]";
 	echo "";
 	echo "### Launch an analysis through (by order of priority):";
 	#echo "# --analysis a configuration file ";
@@ -56,7 +56,7 @@ function usage {
 	echo "# --reads=<FILE1,FILE2...>                 List of Reads files";
 	echo "#                                          For each samples, allowed formats FASTQ|BAM|SAM|CRAM:";
 	echo "#                                          *fastq.gz|*fq.gz|*bam|*ubam|*cram|*ucram|*sam|*usam";
-	echo "# --runs=<FOLDER1,FOLDER2...>              List of RUNs to analyse";
+	echo "# --run=<FOLDER1,FOLDER2...>               List of RUNs to analyse";
 	echo "#                                          From Illumina sequencers (BCL), demultiplexing (FASTQ), or any folder containing FASTQ|BAM|SAM|CRAM.";
 	echo "#                                          For folder containing FASTQ, corresponding Paired-End Read2 will be autodetected: /.*[._-])R1([._-].*/.*[._-])R2([._-].*/";
 	echo "#                                          RUN can be a folder path, or the run folder in defined runs folders (see Application configuration)";
@@ -99,7 +99,24 @@ function usage {
 	echo "#                                          Default: found in RUN folder";
 	echo "# --sample_filter=<STRING1,STRING2...>     List of SAMPLE name in Illumina SampleSheet.csv to analyse";
 	echo "#                                          Default: all samples in the SampleSheet ";
+	echo "# --demultiplexing_only                    Perform only demultiplexing (do NOT analysis FASTQ)";
 	echo "";
+
+	echo "### Folder options";
+	echo "# --input=<FOLDER>                         Input folder (Default: Defined in Application).";
+	echo "#                                          Contains folders 'runs' and 'manifests' to analyse Illumina RUN (see --run option)";
+	echo "# --output=<FOLDER>                        Output folder (Default: Defined in Application).";
+	echo "#                                          Contains folders 'demultiplexing', 'results', 'log' and 'tmp'";
+	echo "# --demultiplexing=<FOLDER>                Output/demultiplexing folder";
+	echo "# --results=<FOLDER>                       Output/results directory to generate RESULTS|RUN|SAMPLE|* files";
+	echo "# --log=<FOLDER>                           Output/log directory to generate RESULTS|RUN|SAMPLE|* files";
+	echo "# --tmp=<FOLDER>                           Output/tmp directory to generate RESULTS|RUN|SAMPLE|* files";
+	echo "#                                          Default: Defined in Application, or first --fastq file folder";
+	echo "# --repository=<FOLDER>                    Repository directory to generate GROUP|PROJECT|RUN|SAMPLE|* specific files";
+	echo "#                                          Default: no copy in a repository";
+	echo "# --archive=<FOLDER>                       Archive directory to generate GROUP|PROJECT|RUN|SAMPLE|* specific files";
+	echo "#                                          Default: no copy in a archive";
+	echo "# --databases=<FOLDER>                     Databases folder (requires STARK databases folder structure)";
 
 	echo "### Other options";
 	echo "# --analysis_name=<STRING>                 Analysis name.";
@@ -121,12 +138,6 @@ function usage {
 	echo "#                                          OR force TRANSCRIPTS file for RUN analysis (use only one TRANSCRIPTS file).";
 	echo "#                                          Format: TSV (transcript<TAB>geneID).";
 	echo "#                                          Default first TRANSCRIPTS file or empty";
-	echo "# --results=<FOLDER>                       Output/results directory to generate RESULTS|RUN|SAMPLE|* files";
-	echo "#                                          Default: Defined in Application, or first --fastq file folder";
-	echo "# --repository=<FOLDER>                    Repository directory to generate GROUP|PROJECT|RUN|SAMPLE|* specific files";
-	echo "#                                          Default: no copy in a repository";
-	echo "# --archive=<FOLDER>                       Archive directory to generate GROUP|PROJECT|RUN|SAMPLE|* specific files";
-	echo "#                                          Default: no copy in a archive";
 	echo "# --threads=<INTEGER>                      Number of thread to use";
 	echo "#                                          Default: all cores in your system minus one";
 	echo "# --by_sample                              Split analysis by SAMPLE, all threads on each sample, one by one.";
@@ -163,7 +174,7 @@ function usage {
 # Getting parameters from the input
 #-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 # ":" tells that the option has a required argument, "::" tells that the option has an optional argument, no ":" tells no argument
-ARGS=$(getopt -o "a:b:e:r:f:q:g:j:m:l:s:w:t:o:u:iygxvdnh" --long "env:,app:,application:,runs:,fastq:,reads:,reads1:,fastq_R1:,by_sample,fastq_R2:,reads2:,index1:,index2:,other_files:,analysis_tag:,sample_tag:,adapters:,analysis:,analysis_name:,analysis_dir:,samplesheet:,sample:,sample_filter:,design:,bed:,manifest:,genes:,transcripts:,threads:,output:,results:,repository:,archive:,no_header,applications_infos,pipelines_infos,release_infos,tools_infos,databases_infos,verbose,debug,release,help" -- "$@" 2> /dev/null)
+ARGS=$(getopt -o "a:b:e:r:f:q:g:j:m:l:s:w:t:o:u:iygxvdnh" --long "env:,app:,application:,runs:,run:,fastq:,reads:,reads1:,fastq_R1:,by_sample,fastq_R2:,reads2:,index1:,index2:,other_files:,analysis_tag:,sample_tag:,adapters:,analysis:,analysis_name:,analysis_dir:,demultiplexing:,demultiplexing_only,samplesheet:,sample:,sample_filter:,design:,bed:,manifest:,genes:,transcripts:,threads:,output:,results:,repository:,archive:,databases:,input:,output:,tmp:,log:,no_header,applications_infos,pipelines_infos,release_infos,tools_infos,databases_infos,verbose,debug,release,help" -- "$@" 2> /dev/null)
 #ARGS=$(getopt -o "e:r:f:l:w:t:iygxvdnh" --long "env:,app:,application:,runs:,fastq:,fastq_R1:,json:,ana:,analysis:,samplesheet:,threads:,application_infos,applications_infos,pipelines_infos,release_infos,tools_infos,databases_infos,verbose,debug,release,help" -- "$@" 2> /dev/null)
 #ARGS=$(getopt -o "e:r:f:l:s:w:t:iygxvdnh" --long "env:,app:,application:,runs:,fastq:,fastq_R1:,analysis:,analysis_name:,analysis_dir:,samplesheet:,sample:,sample_list:,threads:,no_header,application_infos,applications_infos,pipelines_infos,release_infos,tools_infos,databases_infos,verbose,debug,release,help" -- "$@" )
 # || [ -z $@ ]
@@ -196,7 +207,7 @@ do
 			APP="$2"
 			shift 2
 			;;
-		-r|--runs)
+		-r|--run|--runs)
 			RUNS="$2"
 			shift 2
 			;;
@@ -238,6 +249,10 @@ do
 			SAMPLESHEET_INPUT="$2" #"$(echo $2 | tr "\n" " ")"
 			shift 2
 			;;
+		--demultiplexing_only)
+			DEMULTIPLEXING_ONLY=1
+			shift 1
+			;;
 		-s|--sample)
 			SAMPLE="$2"
 			SAMPLE=$(echo $SAMPLE | tr "," " ")
@@ -267,16 +282,40 @@ do
 			TRANSCRIPTS_INPUT=$(echo $TRANSCRIPTS_INPUT | tr "," " ")
 			shift 2
 			;;
-		-o|--output|--results)
-			OUTPUT="$2"
-			shift 2
-			;;
 		-u|--repository)
 			REPOSITORY="$2"
 			shift 2
 			;;
 		--archive)
 			ARCHIVE="$2"
+			shift 2
+			;;
+		--databases)
+			DATABASES="$2"
+			shift 2
+			;;
+		--input)
+			INPUT="$2"
+			shift 2
+			;;
+		--output)
+			OUTPUT="$2"
+			shift 2
+			;;
+		-o|--results)
+			RESULTS="$2"
+			shift 2
+			;;
+		--demultiplexing)
+			DEMULTIPLEXING="$2" #"$(echo $2 | tr "\n" " ")"
+			shift 2
+			;;
+		--tmp)
+			TMP="$2"
+			shift 2
+			;;
+		--log)
+			LOG="$2"
 			shift 2
 			;;
 		-i|--applications_infos)
@@ -354,7 +393,7 @@ done
 # Checking the input parameter
 #--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 if [ -z "$FASTQ" ] && [ -z "$RUNS" ] && [ -z "$ANALYSIS" ] && [ -z "$APPLICATIONS_INFOS" ] && [ -z "$PIPELINES_INFOS" ] && [ -z "$RELEASE_INFOS" ] && [ -z "$TOOLS_INFOS" ] && [ -z "$DATABASES_INFOS" ] && ((!$DEBUG)); then
-	echo "#[ERROR] Required parameter: --analysis, --runs, or --fastq. For informations --applications_infos, --pipelines_infos, --release_infos, --tools_infos. Use --help to display the help." && echo "" && usage && exit 1;
+	echo "#[ERROR] Required parameter: --analysis, --run, or --reads. For informations --applications_infos, --pipelines_infos, --release_infos, --tools_infos. Use --help to display the help." && echo "" && usage && exit 1;
 fi
 #--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 
@@ -371,6 +410,9 @@ if [ "$FASTQ" == "ollow" ] && [ "$THREADS_INPUT" == "he" ] && [ "$W" == "hite" ]
 fi;
 #echo "if [ "$FASTQ" == "ollow" ] && [ "$THREADS_INPUT" == "he" ] && [ "$W" == "hite" ] && [ "$RUNS" == "abbit" ];"
 #exit 0;
+
+
+
 
 # ENV
 #########
@@ -393,12 +435,23 @@ export APP
 EXEC=1
 
 if ((0)) && (($DEBUG)); then
+#if (($DEBUG)); then
 	echo $STARK_FOLDER_BIN
 	echo $STARK_FOLDER_APPS
 	echo $STARK_FOLDER_DOCS
 	echo $STARK_FOLDER_TOOLBOX
 	echo $STARK_FOLDER_CONFIG
 	echo $STARK_FOLDER
+	echo "FOLDER_INPUT:$FOLDER_INPUT"
+	echo "   FOLDER_RUN:$FOLDER_RUN"
+	echo "   FOLDER_MANIFEST:$FOLDER_MANIFEST"
+	echo "FOLDER_OUTPUT:$FOLDER_OUTPUT"
+	echo "   FOLDER_RESULTS:$FOLDER_RESULTS"
+	echo "   FOLDER_DEMULTIPLEXING:$FOLDER_DEMULTIPLEXING"
+	echo "   FOLDER_TMP:$FOLDER_TMP"
+	echo "   FOLDER_LOG:$FOLDER_LOG"
+	echo "DATABASES:$DATABASES"
+	echo "FOLDER_DATABASES:$FOLDER_DATABASES"
 	echo "APP=$APP"
 	echo "ASSEMBLY=$ASSEMBLY"
 	echo "PIPELINES=$PIPELINES"
@@ -731,9 +784,18 @@ if [ "$ANALYSIS" != "" ]; then
 		if [ -f $J ]; then
 
 			echo "#[INFO] Config file '$J' does exists."
+
+ 			(($DEBUG)) && cat $J
+
 			PARAM_ANALYSIS=$(echo "$PARAM " | sed "s/--analysis=[^ |$]*//gi" | sed "s/-w [^ |$]*//gi")
 
-			PARAM_STARK="$($STARK_FOLDER_BIN/json_to_options.py $J)"
+			PARAM_STARK_TEST=0
+			PARAM_STARK="$($STARK_FOLDER_BIN/json_to_options.py $J)" && PARAM_STARK_TEST=1
+
+			! (($PARAM_STARK_TEST)) && echo "[ERROR] Config file '$J' malformed " && cat $J && exit 0;
+
+			#(($DEBUG)) && echo "[INFO] PARAM_STARK=$PARAM_STARK" && exit 0;
+
 			#ANALYSIS_DIR=$(dirname $J)
 			ANALYSIS_DIR=$(cd "$( dirname $J )" && pwd)
 			PARAM_STARK=" --analysis_dir=$ANALYSIS_DIR $PARAM_STARK"
@@ -902,6 +964,11 @@ if [ ! -z "$RUNS" ]; then
 				[ ! -e $RUN_SAMPLESHEET ] && echo "#[ERROR] No SampleSheet for RUN '$R'" && exit 0;
 				echo "#[INFO] SampleSheet found for RUN '$R': $RUN_SAMPLESHEET";
 
+				# DEMULTIPLEXING_FOLDER
+				[ "$DEMULTIPLEXING" != "" ] && DEMULTIPLEXING_FOLDER=$DEMULTIPLEXING;
+				mkdir -p $DEMULTIPLEXING_FOLDER;
+				[ ! -d $DEMULTIPLEXING_FOLDER ] && echo "[ERROR] No demultiplexing folder '$DEMULTIPLEXING_FOLDER'."
+
 				DEM_SAMPLESHEET=$DEMULTIPLEXING_FOLDER/$R_BASENAME/SampleSheet.csv
 				DEM_STARKCOMPLETE=$DEMULTIPLEXING_FOLDER/$R_BASENAME/STARKComplete.txt
 				#DEM_MANIFEST_LIST=$DEMULTIPLEXING_FOLDER/$R_BASENAME/STARKComplete.txt
@@ -920,7 +987,9 @@ if [ ! -z "$RUNS" ]; then
 				# Change RUN folder from RAW to DEM
 				RI="$DEMULTIPLEXING_FOLDER/$R_BASENAME:$R_NAME"
 
-				CMD="$STARK_FOLDER_BIN/STARK $PARAM --run=$RI " #$APP_ONE_RUN_CONFIG_FILE_JSON " # --repository=$FOLDER_REPOSITORY
+				if ! (($DEMULTIPLEXING_ONLY)); then
+					CMD="$STARK_FOLDER_BIN/STARK $PARAM --run=$RI " #$APP_ONE_RUN_CONFIG_FILE_JSON " # --repository=$FOLDER_REPOSITORY
+				fi;
 				#CMD=""
 
 				#echo ""
@@ -943,7 +1012,7 @@ if [ ! -z "$RUNS" ]; then
 				# sampleSheet within the RUN folder
 				[ -z $RUN_SAMPLESHEET ] && RUN_SAMPLESHEET=$R/SampleSheet.csv
 				# Echo
-				(($DEBUG)) && echo "[ -f $R/SampleSheet.csv ] || [ -f $SAMPLESHEET_INPUT_RI ]";
+				#(($DEBUG)) && echo "[INFO] [ -f $R/SampleSheet.csv ] || [ -f $SAMPLESHEET_INPUT_RI ]";
 				[ ! -e $RUN_SAMPLESHEET ] && echo "#[ERROR] No SampleSheet for RUN '$R'" && exit 0;
 				echo "#[INFO] SampleSheet found for RUN '$R': $RUN_SAMPLESHEET";
 
@@ -1009,9 +1078,13 @@ if [ ! -z "$RUNS" ]; then
 						# P1431B_S6_I1_001.fastq.gz
 						SAMPLE_FASTQ_R1_PATTERN=$SAMPLE_NAME'_S*_R1_*.fastq.gz'
 						SAMPLE_FASTQ_R2_PATTERN=$SAMPLE_NAME'_S*_R2_*.fastq.gz'
+						SAMPLE_FASTQ_I1_PATTERN=$SAMPLE_NAME'_S*_I1_*.fastq.gz'
+						SAMPLE_FASTQ_I2_PATTERN=$SAMPLE_NAME'_S*_I2_*.fastq.gz'
 						#echo $SAMPLE_FASTQ_R1_PATTERN
 						SAMPLE_FASTQ_R1=$(find $R -name "$SAMPLE_FASTQ_R1_PATTERN")
 						SAMPLE_FASTQ_R2=$(find $R -name "$SAMPLE_FASTQ_R2_PATTERN")
+						SAMPLE_FASTQ_I1=$(find $R -name "$SAMPLE_FASTQ_I1_PATTERN")
+						SAMPLE_FASTQ_I2=$(find $R -name "$SAMPLE_FASTQ_I2_PATTERN")
 						# APP
 						#SAMPLE_APP="$(echo $L | cut -d, -f$SAMPLE_PROJECT_FIELD | awk -F[$TAG_DELIMITER ] '{print $1}' | tr " " "+" | tr "," "+")"
 						# NEW APP extraction format
@@ -1058,7 +1131,7 @@ if [ ! -z "$RUNS" ]; then
 
 						#	echo "SAMPLE_LIST '$SAMPLE_NAME' found in the list '$SAMPLE_LIST'"
 						APP_LIST=$(echo "$APP_LIST $SAMPLE_APP" | tr " " "\n" | sort -u | tr "\n" " ")
-						echo "$SAMPLE_APP,$SAMPLE_ID,$SAMPLE_NAME,$SAMPLE_FASTQ_R1,$SAMPLE_FASTQ_R2,$MANIFEST_FILE,$MANIFEST_GENES_FILE,$MANIFEST_TRANSCRIPTS_FILE,$SAMPLE_TAG" >> $CONFIG_FILE_TAB
+						echo "$SAMPLE_APP,$SAMPLE_ID,$SAMPLE_NAME,$SAMPLE_FASTQ_R1,$SAMPLE_FASTQ_R2,$SAMPLE_FASTQ_I1,$SAMPLE_FASTQ_I2,$MANIFEST_FILE,$MANIFEST_GENES_FILE,$MANIFEST_TRANSCRIPTS_FILE,$SAMPLE_TAG" >> $CONFIG_FILE_TAB
 					#else
 					#	echo "SAMPLE_LIST '$SAMPLE_NAME' NOT found in the list '$SAMPLE_LIST'"
 					fi;
@@ -1097,21 +1170,26 @@ if [ ! -z "$RUNS" ]; then
 					# SAMPLE NAME
 					echo "\"sample\":\""$(cat $APP_ONE_RUN_CONFIG_FILE | sort -u| awk -F"," -v APP=$APP_ONE '$1==APP{print $3}' | tr '\n' ',' | sed s/,$//)"\"," >> $RUN_CONFIG_FILE
 					# SAMPLE NAME
-					echo "\"sample_tag\":\""$(cat $APP_ONE_RUN_CONFIG_FILE | sort -u| awk -F"," -v APP=$APP_ONE '$1==APP{print $9}' | tr '\n' ',' | sed s/,$//)"\"," >> $RUN_CONFIG_FILE
+					echo "\"sample_tag\":\""$(cat $APP_ONE_RUN_CONFIG_FILE | sort -u| awk -F"," -v APP=$APP_ONE '$1==APP{print $11}' | tr '\n' ',' | sed s/,$//)"\"," >> $RUN_CONFIG_FILE
 					# FASTQ R1/R2
 					echo "\"reads1\":\""$(cat $APP_ONE_RUN_CONFIG_FILE | sort -u | awk -F"," -v APP=$APP_ONE '$1==APP{print $4}' | tr '\n' ',' | sed s/,$//)"\"," >> $RUN_CONFIG_FILE
 					echo "\"reads2\":\""$(cat $APP_ONE_RUN_CONFIG_FILE | sort -u| awk -F"," -v APP=$APP_ONE '$1==APP{print $5}' | tr '\n' ',' | sed s/,$//)"\"," >> $RUN_CONFIG_FILE
+					echo "\"index1\":\""$(cat $APP_ONE_RUN_CONFIG_FILE | sort -u| awk -F"," -v APP=$APP_ONE '$1==APP{print $6}' | tr '\n' ',' | sed s/,$//)"\"," >> $RUN_CONFIG_FILE
+					echo "\"index2\":\""$(cat $APP_ONE_RUN_CONFIG_FILE | sort -u| awk -F"," -v APP=$APP_ONE '$1==APP{print $7}' | tr '\n' ',' | sed s/,$//)"\"," >> $RUN_CONFIG_FILE
 					# MANIFEST
-					echo "\"design\":\""$(cat $APP_ONE_RUN_CONFIG_FILE | sort -u| awk -F"," -v APP=$APP_ONE '$1==APP{print $6}' | tr '\n' ',' | sed s/,$//)"\"," >> $RUN_CONFIG_FILE
+					echo "\"design\":\""$(cat $APP_ONE_RUN_CONFIG_FILE | sort -u| awk -F"," -v APP=$APP_ONE '$1==APP{print $8}' | tr '\n' ',' | sed s/,$//)"\"," >> $RUN_CONFIG_FILE
 					# GENES
-					echo "\"genes\":\""$(cat $APP_ONE_RUN_CONFIG_FILE | sort -u| awk -F"," -v APP=$APP_ONE '$1==APP{print $7}' | tr '\n' ',' | sed s/,$//)"\"," >> $RUN_CONFIG_FILE
+					echo "\"genes\":\""$(cat $APP_ONE_RUN_CONFIG_FILE | sort -u| awk -F"," -v APP=$APP_ONE '$1==APP{print $9}' | tr '\n' ',' | sed s/,$//)"\"," >> $RUN_CONFIG_FILE
 					# TRANSCRIPTS
-					echo "\"transcripts\":\""$(cat $APP_ONE_RUN_CONFIG_FILE | sort -u| awk -F"," -v APP=$APP_ONE '$1==APP{print $8}' | tr '\n' ',' | sed s/,$//)"\"," >> $RUN_CONFIG_FILE
+					echo "\"transcripts\":\""$(cat $APP_ONE_RUN_CONFIG_FILE | sort -u| awk -F"," -v APP=$APP_ONE '$1==APP{print $10}' | tr '\n' ',' | sed s/,$//)"\"," >> $RUN_CONFIG_FILE
 
 					# REPOSITORY
 					echo "\"repository\":\"$FOLDER_REPOSITORY\"," >> $RUN_CONFIG_FILE
-					# ARCHOVE
-					echo "\"archive\":\"$FOLDER_ARCHIVE\"" >> $RUN_CONFIG_FILE
+					# ARCHIVE
+					echo "\"archive\":\"$FOLDER_ARCHIVE\"," >> $RUN_CONFIG_FILE
+
+					# SAMPLESHEET
+					echo "\"samplesheet\":\"$RUN_SAMPLESHEET\"" >> $RUN_CONFIG_FILE
 
 					#echo "\"comment\":\"Analysis for APP $APP_ONE\"" >> $RUN_CONFIG_FILE
 					echo "}" >> $RUN_CONFIG_FILE
@@ -1187,8 +1265,8 @@ if [ ! -z "$RUNS" ]; then
 
 			((RI_NUM++))
 
-			(($DEBUG)) && echo "$CMD"
-			eval $CMD  --no_header
+			(($DEBUG)) && echo "[INFO] CMD=$CMD"
+			[ "$CMD" != "" ] && eval $CMD  --no_header
 
 			echo ""
 
